SELECT
pitcher, 
player_name,
game_year, 
game_date, 
p_throws, 
stand, 
balls, 
strikes, 
outs_when_up, 
inning,
inning_topbot,
pitch_type, 
effective_speed, 
release_spin_rate, 
release_pos_x, 
release_pos_y, 
release_pos_z, 
arm_angle,
pfx_x, 
pfx_z, 
plate_x, 
plate_z, 
zone, 
events, 
description, 
ball_flight_type, 
swing, 
CASE WHEN swing = 0 THEN NULL ELSE whiff END as whiff, 
CASE WHEN description = 'hit_into_play' THEN 1 WHEN description = 'foul' THEN 0 ELSE NULL END as bip,
CASE WHEN whiff = 1 OR description = 'called_strike' THEN 1 ELSE 0 END AS csw,
launch_speed, 
launch_angle, 
spray_angle, 
estimated_ba_using_speedangle, 
estimated_woba_using_speedangle, 
estimated_slg_using_speedangle,
woba_value, 
woba_denom, 
babip_value, 
launch_speed_angle, 
CASE WHEN launch_speed_angle = 6 THEN 1 WHEN launch_speed_angle < 6 THEN 0 ELSE NULL END AS barrel,
delta_run_exp
FROM db.statcast
WHERE game_year >= 2023
AND pitch_type in ('FF', 'SI')